version: '3'
services:
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=mysite.settings
      - PORT=8000
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
